# Generated by Django 2.2.20 on 2021-06-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site', '0002_auto_20210609_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id_husband',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_husband',
                                    to='site.Person'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id_wife',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_wife',
                                    to='site.Person'),
        ),
    ]
