# Generated by Django 2.2.20 on 2021-06-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """ Add `null` parameter to fields `id_husband` and `id_wife` """

    dependencies = [
        ('site', '0003_add_related_name_to_id_husband_id_wife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id_husband',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='id_husband',
                to='site.Person'
            ),
        ),
        migrations.AlterField(
            model_name='family',
            name='id_wife',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='id_wife',
                to='site.Person'
            ),
        ),
    ]
