# Generated by Django 2.2.20 on 2021-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """ Add blank parameter to fields `id_husband` and `id_wife` """

    dependencies = [
        ('site', '0004_add_null_parameter_to_id_husband_id_wife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
