# Generated by Django 2.2.20 on 2021-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """ Migration add fields `year_of_birth` and `year_of_death`"""

    dependencies = [
        ('site', '0005_add_blank_parameter_id_husband_id_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='year_of_death',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
