# Generated by Django 2.2.20 on 2021-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site', '0006_add_fields_year_birth_year_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
