# Generated by Django 2.2.20 on 2021-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site', '0007_person_place_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
